# Generated by Django 4.0.5 on 2022-11-20 15:33

import Blog.fields
import Blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('title_image', Blog.fields.WEBPField(default='posts/home-bg.webp', upload_to=Blog.models.image_folder, validators=[Blog.models.validate_image], verbose_name='Image')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('content', tinymce.models.HTMLField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PUB', 'Published'), ('PRI', 'Private')], default='PUB', max_length=3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postgres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
